# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jiselee <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/10/14 17:17:08 by jiselee           #+#    #+#              #
#    Updated: 2020/11/06 21:26:08 by jiselee          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

.PHONY			:	all bonus clean fclean re so

CC				=	gcc

CFLAGS			=	-Wall -Wextra -Werror -I.

NAME			=	libft.a

SRCS			=	ft_isalnum.c ft_isprint.c ft_memcmp.c  ft_putchar_fd.c ft_split.c \
					ft_strlcat.c ft_strncmp.c ft_substr.c ft_atoi.c ft_isalpha.c \
					ft_itoa.c ft_memcpy.c  ft_putendl_fd.c ft_strchr.c  ft_strlcpy.c \
					ft_strnstr.c ft_tolower.c ft_bzero.c   ft_isascii.c ft_memccpy.c \
					ft_memmove.c ft_putnbr_fd.c  ft_strdup.c  ft_strlen.c  ft_strrchr.c \
					ft_toupper.c ft_calloc.c  ft_isdigit.c ft_memchr.c  ft_memset.c  \
					ft_putstr_fd.c  ft_strjoin.c ft_strmapi.c ft_strtrim.c ft_itoa_base.c \

SRCS_B			=	ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c ft_lstadd_back.c \
					ft_lstdelone.c ft_lstclear.c ft_lstiter.c ft_lstmap.c

OBJS			=	$(SRCS:.c=.o)

OBJS_B			=	$(SRCS_B:.c=.o)

all				:	$(NAME)

$(NAME)			:	$(OBJS)
	ar rcs $(NAME) $(OBJS)

bonus			:	$(OBJS_B)
	ar rcs $(NAME) $(OBJS_B)

clean			:
	rm -f $(OBJS) $(OBJS_B)

fclean			:	clean
	rm -f $(NAME)
	rm -f $(NAME:.a=.so)

re				:	fclean all

so				:	$(OBJS)
	$(CC) -shared -fPIC -o libft.so $(OBJS) $(OBJS_B)
